### PR TITLE
Add github action and change readme link

### PR DESCRIPTION
**Pull request by Kn99HN**

### CODE REVIEW

**Review by esilverm — CHANGES_REQUESTED** [review]
This could be problematic. We should look at instead working with netlify to deploy our site.

**Comment by Kn99HN** [comment]
Do you want to use netfiy or vercel?

**Comment by esilverm** [comment]
Either one should work, but I think vercel or netlify would be an improvement upon deploying via gh actions and github sites. Especially since they include build checks for prs and site previews

**Comment by Kn99HN** [comment]
Okie! Do you want me  to also change it for the bugs website as well?

**Comment by esilverm** [comment]
I think we left the bugs website as being deployed via github sites since we are for open source (not really sure if that is exactly why, but I remember Albert making that point). I feel like this is a different kind of deal

**Comment by Kn99HN** [comment]
Yeah ok. sounds good. I'll close this in favor of vercel

**Comment by Kn99HN** [comment]
I just realize for both we need to pay monthly fee since the repo lives in BUGS org ..... We have 14 days trial with vercel. For now, we will go with none until we figure out funding lol

**Comment by esilverm** [comment]
oof, do you think we qualify for this?
Screen Shot 2021-03-07 at 2 45 14 PM

**Comment by Kn99HN** [comment]
Oh I didn't see that. We might. I'll have Laurel and DT handle this since I think we are not in a rush?

**Comment by esilverm** [comment]
This actually may cause the same problem if we decide to move bobcat search over.

**Comment by Kn99HN** [comment]
That's true though I'm unsure when bobcat search will be moved over. I think once it's moved over, we can deal with it. As of rn, we just need to find solution for this repo

**Pull request closed without merging**
