### PR TITLE
add test build

### PR DESCRIPTION
**Pull request by esilverm**
My fault that we didn't commit this. This would be helpful for checking pull requests.

### CODE REVIEW

**Comment by Kn99HN** [comment]
: )

**Comment by esilverm** [comment]
at least it will be helpful until we get netlify's support

**Review by Kn99HN — APPROVED** [review]

**Comment by Kn99HN** [comment]
Oops nvm

**Comment by esilverm** [comment]
im going to debug this... hmm

**Review by Kn99HN — CHANGES_REQUESTED** [review]
Needs some debugging

**Pull request merged**
