### PR TITLE
Add Search Bar

### PR DESCRIPTION
**Pull request by Kn99HN**

### CODE REVIEW

**Review by esilverm — APPROVED** [review]
This should do for now. We could probably use something like algolia to make our search bar more functional and predictive. we may also want to set up a dropdown for search predictions but that can all be added later

**Comment by Kn99HN** [comment]
Makes sense. It's gonna be for aesthetic for now. Smh Evan what are you doing on Sat night reviewing PR lol

**Comment by esilverm** [comment]
> Smh Evan what are you doing on Sat night reviewing PR lol

my gf is sick and went to sleep super early so i'm just chilling in bed reviewing PRs. this is normal 👀

github mobile is amazing btw

**Comment by Kn99HN** [comment]
My gf is also sick rn lol. Never use gh mobile but sounds gud

**Pull request merged**
